### ISSUE TITLE
"providence" isn't a good term

### ISSUE THREAD

**Issue by richsalz** [zmap/zlint#123]
And "provenance" isn't that much better. :) Perhaps just the simple "from"?
providence shows up in the json output format.

**Comment by zakird** [comment]
#124 addresses the incorrect output. I'm personally don't have much opinion on _provenance_ vs _from_. Happy to let others weigh in.

**Comment by richsalz** [comment]
feel free to close this if you like that fancy, but wrong, word :)

**Comment by zakird** [comment]
I agree that provenance isn't the right word, so definitely not going to close. :) Not sure if I'm in love with "from". _source_? _origin_?

**Comment by richsalz** [comment]
Either of those is better than what i suggested, yeah.

**Comment by zakird** [comment]
This is addressed by #145, which renames `Provenance` to `Source`.
