### ISSUE TITLE
Postal code prohibited check is incorrect

### ISSUE THREAD

**Issue by robstradling** [zmap/zlint#157]
Some of the "Prohibited" clauses in BR 7.1.4.2.2 are badly written.  For example (emphasis mine):
- subject:localityName is prohibited "if the subject:organizationName field, subject:givenName, **and** subject:surname field are absent".
- subject:stateOrProvinceName is prohibited "if the subject:organizationName field, subject:givenName field, **or** subject:surname field are absent"
- subject:postalCode is prohibited "if the subject:organizationName field, subject:givenName field, **or** subject:surname field are absent"

I'm sure the intent for all of the above is that the prohibition applies only if **all** of the mentioned fields (organizationName, givenName and surname) are absent.  That's the approach ZLint seems to take for all Subject fields except for subject:postalCode.

https://github.com/zmap/zlint/blob/master/lints/lint_sub_cert_postal_code_prohibited.go#L19 needs `&&`s instead of `||`s.

**Comment by kumarde** [comment]
@robstradling thanks for catching this. When writing these tests I thought it was weird that they used different clauses for each, so I assumed it must have been intentional. I'll fix this.

**Comment by dadrian** [comment]
Fixed by #158

**Comment by robstradling** [comment]
Thanks @kumarde and @dadrian.  :-)
