### ISSUE TITLE
Decide how to handle non-server certificates

### ISSUE THREAD

**Issue by robstradling** [zmap/zlint#167]
Consider the following example certs:
https://crt.sh/?id=204352566&opt=zlint (a Client Authentication certificate)
https://crt.sh/?id=201186679&opt=zlint (an OCSP Signing certificate)
https://crt.sh/?id=122792187&opt=zlint (a Code Signing certificate)
https://crt.sh/?id=158872566&opt=zlint (an EV Code Signing certificate)

Currently ZLint "checks for consistency with RFC 5280 and the CA/Browser Forum Baseline Requirements (v.1.4.8)", so it's unsurprising that various warnings/errors/fatals are triggered for these certs that aren't intended to comply with the CABForum BRs.

Should ZLint be enhanced to somehow detect the certificate type and only run CABForum BR lints on certs that are actually expected to be CABForum BR compliant?  Should ZLint even be further enhanced to check for consistency with other standards (e.g., the EV Code Signing Guidelines, the Code Signing BRs published by CASC, the Google S/MIME profile, the various browser root program policies, etc).

Or, should it be up to the user/caller (e.g., crt.sh) to make sure that ZLint is only used/called for certs that are expected to be CABForum BR compliant?

**Comment by zakird** [comment]
I think it makes sense to update ZLint to detect certificate scope and to execute the correct certificates. I think there are likely two parts of this:

(1) Deciding what logic we want to use to determine whether a certificate falls under CA/B purview. 

(2) Marking lints with their scope.

It sounds like there isn't a clear definition for (1). @pzb had suggested limiting scope to certificates with Server Auth and All auth. If everything agrees that this is the right setting, @kumarde do you want to work on getting that in place?

**Comment by robstradling** [comment]
Where "All auth" means that the EKU extension is either: (1) absent; or (2) present and contains anyExtendedKeyUsage?  SGTM.

**Comment by zakird** [comment]
@robstradling yep

**Comment by zakird** [comment]
Notes:
(1) add programmatic source field. Three options to start: (1) BR, (2) RFC5280, (3) ZLint

**Comment by kumarde** [comment]
Merged.
