### ISSUE TITLE
RFC 5280 Lints should be documented

### ISSUE THREAD

**Issue by zakird** [zmap/zlint#173]
We need to go through the lints we have for RFC5280 and document them in master spreadsheet (https://docs.google.com/spreadsheets/d/1ywp0op9mkTaggigpdF2YMTubepowJ50KQBhc_b00e-Y/edit#gid=0).

Given the number of lints that were missing from the CA/B Forum lints before this was done, I'm not confident that we have actual RFC coverage currently.

**Comment by kumarde** [comment]
RFC5280 Coverage is added to the doc.

**Comment by zakird** [comment]
I am re-opening this issue. This should look like the BR tab and list which lint covers each provision.
