### ISSUE TITLE
Speeding up the slowest lints

### ISSUE THREAD

**Issue by szank** [zmap/zlint#178]
Hi, I was intending to use zlint as a library, and ran some benchmarks to see how it fares.
It turns out that there are five lints (w_dnsname_underscore_in_trd, e_dnsname_underscore_in_sld, e_dnsname_hyphen_in_sld, w_dnsname_wildcard_left_of_public_suffix, w_san_iana_pub_suffix_empty) that slow down the linter tremendously. Without them the linter runs ~70x faster on my laptop. The current performance is too low for my needs. 

The mentioned linters are so slow, because they all call `util.ICANNPublicSuffixParse` on CommonName and SAN DNS names. 

I'd like to propose a meta linter, that first parses the strings with `util.ICANNPublicSuffixParse` and then performs all the checks, on already parsed values. 

This way you could sped up the linter ~5x. 
It would also require Linter interface change, from 
`Execute(c *x509.Certificate) *LintResult` to `Execute(c *x509.Certificate) []LintResult`

Otherwise, the parsed domain names could be cached in the zcrypto's x509 certificate. 
I am hoping to start a discussion on how to make the zlint faster, and I'd be happy to write a PR for that if I get a green light.

**Comment by zakird** [comment]
Thanks for your note. I agree that it makes sense to cache this processing if it'll provide a significant speedup. I suspect it'll be better to add a call to the ZCrypto library (i.e., a function on the certificate object that caches it after being run the first time) such that we don't need to track state between lints in ZLint and can make the change without any API modification.

I also suspect that we could also implement a very simple version of the library that handles 95%+ of cases and only have to call out to this library for edge cases.

Does that seem reasonable??

/cc @dadrian @titanous

**Comment by dadrian** [comment]
> I also suspect that we could also implement a very simple version of the library that handles 95%+ of cases and only have to call out to this library for edge cases.

I don't follow what you mean here, but everything else sounds reasonable.

**Comment by szank** [comment]
Hey, 
Thanks for the quick reply. 
I have ran a quick benchmark comparing the old code and the optimised one: 
```
benchcmp old.benchmarks.txt new.benchmarks.txt
benchmark                        old ns/op     new ns/op     delta
BenchmarkZlint/All_lints         40174032      555150        -98.62%
BenchmarkZlint/All_lints-4       32186170      457134        -98.58%
BenchmarkZlint/All_lints-8       32447556      458518        -98.59%
BenchmarkZlint/All_lints-16      32776078      462352        -98.59%
BenchmarkZlint/All_lints-64      33382044      465761        -98.60%
BenchmarkZlint/All_lints-128     33593336      467877        -98.61%
```
Strangely enough the delta value is wonky, as the new code is ~70x faster. 
The benchmark results above doesn't include the time it takes to parse the x509 certificate used as input to the linter. 

I have added a new field to the x509.Certificate, that stores the parsed domain names. I have benchmarked it and there is a tiny bit of slowdown, which was expected, unfortunately.
```
benchcmp old.benchmarks.txt new.benchmarks.txt
benchmark                         old ns/op     new ns/op     delta
BenchmarkParseCertificate         110414        109535        -0.80%
BenchmarkParseCertificate-4       81015         80667         -0.43%
BenchmarkParseCertificate-8       81437         80874         -0.69%
BenchmarkParseCertificate-16      81656         81333         -0.40%
BenchmarkParseCertificate-64      82078         82206         +0.16%
BenchmarkParseCertificate-128     83174         85284         +2.54%
```

I don't know what to think about the BenchmarkParseCertificate-128, i would blame running it on a laptop.

The certificate used in both benchmarks have 41 SAN DNS names. Obviously the speedup will be lower if the input certificate has less entries in the SAN extension, but the validation will still be faster. And there are certificates in the wild with hundreds of SANs.

 If I get a green light here, I will proceed with a PR for the zcrypto repo, to add the required field to the cert struct.

**Comment by zakird** [comment]
Sounds good to me. It might be nice to have this be lazily loaded (i.e., make it a method that you compute and cache instead of running when Parse is called).
