### ISSUE TITLE
Spurious e_dnsname_bad_character_in_label errors due to PR #179

### ISSUE THREAD

**Issue by robstradling** [zmap/zlint#180]
PR #179 definitely speeds things up, so thanks for that.  :-)

However, having just updated zlint to https://github.com/zmap/zlint/commit/36a643fb3d1d4e92d7de5056003fda59676d18ea on the crt.sh servers, I'm now seeing most certs being incorrectly flagged with the e_dnsname_bad_character_in_label error.

**Comment by robstradling** [comment]
Just to clarify: I've only updated zlint on the crt.sh master DB server so far, which affects https://crt.sh/?zlint=1+week but not the certificate pages (such as https://crt.sh/?id=3&opt=zlint).

**Comment by szank** [comment]
Damn. Thanks for fixing this! 
I am surprised that the old regex have compiled.
