### ISSUE TITLE
Generating certificates for unit tests

### ISSUE THREAD

**Issue by szank** [zmap/zlint#183]
Hi guys, I wanted to add few more lints and need to generate certificates that would fail those lints. 
Are there any guidelines on how to generate them?
I can see that the subject/issuer are similar in most of them. Shall I reuse those? 
Are you using self signed certs? Any easy way to generate ones? If not, I could write a tool that would create a self signed cert from a template and put it in the repo also.

**Comment by zakird** [comment]
@kumarde is going to get back to you about how we've been creating certificates.

**Comment by szank** [comment]
Thanks ! :)

**Comment by kumarde** [comment]
Hi @szank,

Thus far, we've been using a built-in Go function:(https://golang.org/pkg/crypto/x509/#CreateCertificate) to create certificates that modify the appropriate fields. I've been less concerned about the fields that are unrelated to the test at hand (for example, if the SAN extension is being tested, I haven't cared much about the `issuer_dn`). 

If you'd like to create a simple tool using that Go function to create a self signed cert from a template, that would be awesome.

**Comment by szank** [comment]
I was wondering if it would be better to just generate an appropriate cert structure and fill it in for each unit test. 
The linters input does not have to be signed, nor it needs all fields required in the valid x509 certificate. 

I would have to create such template anyway, but signing it, saving it to file and then parsing the file when running unit tests seems completely unnecessary to me.

**Comment by szank** [comment]
Turns out that there is no good way to make an universal tool to generate test certificates. Too much fiddling with the certificate internals that have to be tailored for each and every test. 
Closing the issue.
