### ISSUE TITLE
w_serial_number_low_entropy lint should return an error: 

### ISSUE THREAD

**Issue by szank** [zmap/zlint#187]
Suprisingly, some CAs can't get even this right: 
https://crt.sh/?id=277579245&opt=cablint,x509lint,zlint

As per the CA/B BR wording this should be an error. Any objections ?

**Comment by szank** [comment]
The definitely could do better: https://crt.sh/?id=277426104&opt=x509lint,zlint,cablint

**Comment by zakird** [comment]
Agree, this looks more like an error than a warning given the `SHALL`.

**Comment by titanous** [comment]
This is intentionally not an error as it's not possible to programmatically detect a violation of this clause with 100% accuracy: https://github.com/zmap/zlint/pull/112#issuecomment-324677507

**Comment by szank** [comment]
Sigh that's fair enough. It have been some time since I have read about the reasoning about this requirement. It was about a known prefix attack, right ?

The question is, does the missing bytes in the serial number ( if they CSPRNG outputs  bits with leading zeroes ) facilitate the attack> I guess not, because the length of the prefix cannot be predicted anyway in such case. Can someone please correct me here? 
I am not very keen on digging into it again. 

If encoding the serial number on smaller number of bytes makes the attack easier, I think this lint should return an error in the end. It is trivial to prepend the output from the CSPRNG with a fixed byte > 0 if one wanted to enforce a minimum byte length of the SN.

**Comment by titanous** [comment]
> Sigh that's fair enough. It have been some time since I have read about the reasoning about this requirement. It was about a known prefix attack, right ?

It was introduced in response to the MD5/SHA-1 weaknesses in order to change the level of attack necessary to forge a certificate with a broken hash algorithm from chosen-prefix collision to random-prefix collision: https://cabforum.org/pipermail/public/2016-June/007858.html

> The question is, does the missing bytes in the serial number ( if they CSPRNG outputs bits with leading zeroes ) facilitate the attack> I guess not, because the length of the prefix cannot be predicted anyway in such case. Can someone please correct me here?

No, the byte length itself doesn't matter.

> If encoding the serial number on smaller number of bytes makes the attack easier, I think this lint should return an error in the end. It is trivial to prepend the output from the CSPRNG with a fixed byte > 0 if one wanted to enforce a minimum byte length of the SN.

While this is trivial, it is not required by the Baseline Requirements, and so I don't think it's reasonable to trigger an error given that a few CAs do not do this and appear to generate exactly 64 bits of entropy before encoding it as the serial number.

**Comment by zakird** [comment]
It looks like this has been addressed in the conversation here. I'm going to close this issue.
