### ISSUE TITLE
dNSName lints should not be applied to iPAddress fields

### ISSUE THREAD

**Issue by robstradling** [zmap/zlint#189]
https://crt.sh/?id=284927361&opt=zlint
"DNSNames must have a valid TLD"

I'm not sure if it's complaining about the IPv4 address in the Subject CN field or in the SAN iPAddress field.  Either way, it's a false positive.

**Comment by kumarde** [comment]
Good point. It's complaining about the CN field. In fact, we should probably check that the CN field is NOT an IP address before we do any sort of DNS-related checks. I can submit a PR to this effect.

**Comment by zakird** [comment]
I believe this has been addressed by #190 and that this was added as a test case, which is passing As such, I'm going to close this issue.
