### ISSUE TITLE
Lint "e_subject_dn_country_not_printable_string" is too strict

### ISSUE THREAD

**Issue by szank** [zmap/zlint#197]
Hi, this is a bit embarrassing, but I've had another read through the RFC 5280 (https://tools.ietf.org/html/rfc5280#section-4.1.2.4)
and it states that for both Issuer and Subject the RDN fields can be either PrintableString or UTF8String. 
```
The DirectoryString type is defined as a choice of PrintableString,
   TeletexString, BMPString, UTF8String, and UniversalString.  CAs
   conforming to this profile MUST use either the PrintableString or
   UTF8String encoding of DirectoryString, with two exceptions.  When
   CAs have previously issued certificates with issuer fields with
   attributes encoded using TeletexString, BMPString, or
   UniversalString, then the CA MAY continue to use these encodings of
   the DirectoryString to preserve backward compatibility.  Also, new
   CAs that are added to a domain where existing CAs issue certificates
   with issuer fields with attributes encoded using TeletexString,
   BMPString, or UniversalString MAY encode attributes that they share
   with the existing CAs using the same encodings as the existing CAs
   use.
```
The Appendix A that is used as the citation for the lint is wrong, or at least inconsistent. Also, I think that this should be a warning, given the allowed exceptions.

**Comment by robstradling** [comment]
That paragraph is about DirectoryString.  The countryName DN field is defined as a PrintableString, *not* as a DirectoryString.
I recommend closing this ticket as invalid.

**Comment by zakird** [comment]
My reading of 5280 matches Rob's. Closing.

**Comment by szank** [comment]
Thanks for the input. I assumed incorrectly that all the fields in the RDN are Directory strings. The "Issuer" section in the RFC does imply that. If the consensus is that Appendix A overrides this, which seems valid then this issue is invalid indeed.
