### ISSUE TITLE
w_dnsname_underscore_in_trd should not be a warning

### ISSUE THREAD

**Issue by RufusJWB** [zmap/zlint#204]
According to https://stackoverflow.com/a/2183140 it is perfectly okay to have underscores in domain names. But zlint creates a warning https://crt.sh/?id=206304439&opt=zlint and I can't find a place in the BRGs where it is explicitly forbidden. I would suggest to change this.

**Comment by zakird** [comment]
This is somewhat undefined. There was a CA/B ballot over whether underscores are allowed, but this failed. See: https://cabforum.org/2017/07/26/ballot-202-underscore-wildcard-characters/. For more context, see https://www.mail-archive.com/dev-security-policy@lists.mozilla.org/msg02548.html. At the end of the day, given this ambiguity, I think it goes against community best practices to allow underscores, and makes sense to remain as a warning.

**Comment by RufusJWB** [comment]
Thank you for pointing out the discussion on m.d.s.p . As I understand the discussion, the point with the underscore is not so much topic of the CAs but how browsers are resolving domain names / host names. Since in practice there are hundreds of thousands of domain names with underscores out in the field, which are perfectly reachable from the internet, even if it is unclear if those names are compliant with all RFCs,, I would like to propose that you rate this issue down from warning to notice / info, since the problem here is clearly not the CA but that the RFCs about domain names are

> a special hell. It is dark and scary. You are likely to be eaten by a grue.

**Comment by zakird** [comment]
Thanks. Unfortunately though ZLint is designed with CAs in mind. Just because those names has been registered (or are reachable) doesn't mean that CAs can correctly sign certificates for them.

**Comment by RufusJWB** [comment]
If I understand the discussion correctly, it is not even clear, whether underscores are valid characters  according to the RFCs in FQDNs or not. If you compare the link to [SO](https://stackoverflow.com/a/2183140) it seems to be legit and also the voting results to ballot 202 underline, that the vast majority of CAs and Browsers (incl. Google) share this understanding. Therefore I still think it would be adequate to flag this not as a warning but as an info / note by ZLINT.

**Comment by titanous** [comment]
dNSName SANs as implemented in the WebPKI are intended to be TLS server hostnames, and underscores are not allowed in DNS hostnames. The fact that some DNS resolvers and clients are lax in their handling of the specifications does not cause the RFCs to change.

I'm not so sure that the "vast majority" of CAs and browsers share your understanding of the situation. For example, Let's Encrypt does not allow underscores (letsencrypt/boulder#1225), and many platforms and clients do not allow underscores in hostnames: https://support.industry.siemens.com/cs/document/67794551/why-is-the-underscore-character-not-permitted-in-computer-names-in-pcs-7-

Given the ambiguity, I think this should definitely stay as a warning.

**Comment by titanous** [comment]
For reference, there are very few certificates that trigger this warning: https://crt.sh/?zlint=922&dir=^&sort=1&minNotBefore=2017-01-01

**Comment by zakird** [comment]
While a number of groups voted in favor of the proposal, it did not pass. We cannot apply our own voting rules on top of another organization. As Jonathon points out, dNSNames are intended to represent DNS hostnames, which do not permit underscores.

**Comment by RufusJWB** [comment]
@titanous wrote

> I'm not so sure that the "vast majority" of CAs and browsers share your understanding of the situation.

Well, in Ballot [202 ](https://cabforum.org/2017/07/26/ballot-202-underscore-wildcard-characters/)63% of the CAs and 100% of the browsers voted "Yes" to allow the underscore character explicitly. So i think, the "vast majority"was in favor, but the Bylaw 2.2(f) requiring a two-third-majority of the CAs was not reached.

Exactly due to the ambiguity I think it should be seen only as an info / note and not a warning, but at the end, it's your software not mine.

**Comment by zakird** [comment]
I also want to quickly clarify that this is not an `error`, but a `warning`. Errors represent explicitly violating a standards document (e.g., a `MUST NOT`) in an RFC. `warnings` represent violating best practices or community standards (e.g., an RFC `SHOULD NOT`). We view performing an action that is questionably incorrect (and is in conflict with a failed ballot to permit) as violating best practices.

**Comment by RufusJWB** [comment]
@zakird Thank you for your clarification. The background of rising this topic is, that we are striving to operate our CA in the future without any `warning` from the LINTer. To reach this goal we will have to reject CSRs for FQDNs which are perfectly okay in all browsers just because of some 'ambiguity' in 40 years old RFCs. This is not really user-centric but it is as it is.
