### ISSUE TITLE
E: EV certificates must include localityName in subject - only true if stateOrProvinceName is absent

### ISSUE THREAD

**Issue by Santhanraj** [zmap/zlint#225]
This shouldn't be an error since localtyName is optional when stateOrProvinceName is present (since EV ver 1.6.4 and ballot 191)

E.g., https://crt.sh/?id=466655384&opt=zlint

BR: 7.1.4.2.2 (e)
Certificate Field: subject:localityName (OID: 2.5.4.7)
Required if the subject:organizationName field, subject:givenName field, or subject:surname field are present and the subject:stateOrProvinceName field is absent.
Optional if the subject:stateOrProvinceName field and the subject:organizationName field, subject:givenName field, or subject:surname field are present.
Prohibited if the subject:organizationName field, subject:givenName, and subject:surname field are absent.

**Comment by zakird** [comment]
@kumarde can you take a look at getting this fixed up?

**Comment by zakird** [comment]
This is addressed by #230.
