### ISSUE TITLE
Give TLD data and associated lints effective periods

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#235]
## Background

This is a follow-up issue from the discussion in https://github.com/zmap/zlint/pull/233 - to summarize the problem:
IANA occasionally deprecates a gTLD. The existing [`updateTLDs.sh` script](https://github.com/zmap/zlint/blob/02fe9a29bbae57da0c77db7afb53734dc262b130/updateTLDs.sh) removes deprecated gTLDs from the [generated `tldMap` data](https://github.com/zmap/zlint/blob/848521ffb4ee6042d34faf7389e970d149a84d91/util/gtld_map.go#L17). This results in false-positive linting failures for previously issued certificates with subject domains using the previously valid gTLD. 

To properly reflect gTLD's having effective periods the `tldMap` and its associated generation process shouldn't remove gTLDs but instead set a "notafter" date in the data matching the IANA deprecation date. Similarly when a new gTLD is added the `tldMap` should be updated with an entry for the new gTLD that sets the "notbefore" date in the mapping to the time IANA added the gTLD entry. The associated linters should be updated to check that the certificate's issuance date is coherent with the associated subject identifier gTLD effective period. This catches invalid issuance for retired/not-yet-introduced gTLDs while not introducing false-positives for valid certificates when a gTLD is deprecated.

## Proposed Implementation

I'm happy to submit a PR for this issue. Here's a rough outline of how I'd approach this:

* add a `GTLDPeriod` type to `util/` for capturing a start/end `time.Date`
* change the `util/gtld_map.go` `tldMap` from `map[string]bool` to `map[string]GTLDPeriod`
* update the linters to use the `GTLDPeriod` information
* Replace `updateTLDs.sh` and `scripts/consolodate_tlds.py` with a Go cmd (`zlint-gtld-update`?) that writes a `map[string]GTLDPeriod`
* Update `util/gtld_map.go` to use `go generate zlint-gtld-update`

@zakird Does the above sound reasonable to you? If you'd prefer to keep the utility for this split across BASH/Python I can make that work but I lightly prefer using Go throughout. If the above looks good I can get started on a PR this week.

**Comment by zakird** [comment]
This sounds spot-on to me.

**Comment by cpu** [comment]
@zakird Great, thanks for confirming. I'll get started and we can hash out the fine details in the PR review.

**Comment by cpu** [comment]
Here's my initial PR: https://github.com/zmap/zlint/pull/236
