### ISSUE TITLE
zlint	ERROR	Root CA Certificate: extendedKeyUsage MUST NOT be present.t

### ISSUE THREAD

**Issue by Pieter-1337** [zmap/zlint#257]
Hi, I am currently creating a root certificate which can sign a San certificate.
I am using following powershell command to create the Root: `$rootCert = New-SelfSignedCertificate -CertStoreLocation cert:\LocalMachine\My -keyUsage KeyEncipherment,DigitalSignature,CrlSign,CertSign -Subject "CN=AgionRootCA, OU=supplied, O=supplied, C=BE, L=supplied, S=supplied"  -TextExtension @("1.3.6.1.4.1.311.21.10={text}1.3.6.1.5.5.7.3.1,1.3.6.1.5.5.7.3.2", "2.5.29.19={text}CA=true","2.5.29.37={text}1.3.6.1.4.1.311.10.12.1")`

However I am getting following error out of your z-lint: zlint	ERROR	Root CA Certificate: extendedKeyUsage MUST NOT be present.t

I am not using -extendedKeyUsage anywhere in my command? What exactly should I do to fix this problem?

**Comment by kumarde** [comment]
OIDD 2.5.29.37 is ExtendedKeyUsage, which I see you've added in the `TextExtension` field.

**Comment by Pieter-1337** [comment]
@kumarde  Thank you for the awnser this did resolve my issue :)
