### ISSUE TITLE
Add Go module support, pin dependencies

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#264]
Supporting [Go modules](https://github.com/golang/go/wiki/Modules) would make `zlint`'s dependencies explicit. This would help with situations like the one discussed in https://github.com/zmap/zlint/pull/263 where a lint may depend on new functionality in `zcrypto`.

There are alternatives to Go modules for tracking dependencies (godeps, gvt, etc) but [Go 1.13+](https://blog.golang.org/modules2019) will make modules supported by default and I expect much of the Go ecosystem will standardize on modules vs the alternatives.

**Comment by dadrian** [comment]
I strongly agree with this.

**Comment by cpu** [comment]
@dadrian Great! Related to module support do you have any thoughts about whether to commit vendored dependencies to the repo or not?

I'm generally in favour of doing that because it makes builds faster and helps eliminate occasional flakyness from `go get` but I understand that some folks in the Go community think its unnecessary since the vendored deps can be reconstructed from the `go.mod`.

**Comment by zakird** [comment]
I don't have any issue with vendorizing the dependencies.

**Comment by cpu** [comment]
I have a PR for this up for review: https://github.com/zmap/zlint/pull/266
