### ISSUE TITLE
e_qcstatem_qclimitvalue_valid crashes

### ISSUE THREAD

**Issue by zakird** [zmap/zlint#274]
The `e_qcstatem_qclimitvalue_valid` line causes Go panic for some certificates. I have temporarily commented out the specific lint, but we need to go back and fix the underlying problem. This certificate triggers the crash:
[qcstatement_crash_zlint.txt](https://github.com/zmap/zlint/files/3024992/qcstatement_crash_zlint.txt)

**Comment by cpu** [comment]
I was able to reproduce and fix the immediate bug: https://github.com/zmap/zlint/pull/276
