### ISSUE TITLE
ct_sct_policy_count_unsatisfied should ignore precertificates

### ISSUE THREAD

**Issue by jsha** [zmap/zlint#298]
Follow up to https://github.com/zmap/zlint/pull/278. Since precertificates never have SCTs, the ct_sct_policy_count_unsatisfied linter should ignore precertificates.

Related also to https://github.com/letsencrypt/boulder/pull/4378.

**Comment by cpu** [comment]
:+1: I'll work on a fix for this shortly.

**Comment by cpu** [comment]
> I'll work on a fix for this shortly.

As promised: https://github.com/zmap/zlint/pull/299
