### ISSUE TITLE
Consider semver releases

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#307]
Adopting [semver](https://semver.org/) and tagged releases would help relying projects avoid breakages like described in https://github.com/zmap/zlint/issues/305 and is a best practice for Go module projects. Presently most projects will track master or have to pick fixed commits manually.

What do other folks think?

**Comment by cardonator** [comment]
In my opinion, it only makes sense to adopt Semver and make the releases compatible with the Go module system.

**Comment by zakird** [comment]
Yes please! I had originally planned to release 1.0.0 when all of the lints had tests, but given that it's already in production at a number of places, I don't think it makes sense to block on that.

**Comment by cpu** [comment]
:ballot_box_with_check: - https://github.com/zmap/zlint/releases/tag/v1.0.0

I updated the README with [some guidance](https://github.com/zmap/zlint/pull/310) to keep in mind as we move forward with zlint maintenance in a semver world.

Thanks for the input everyone, congrats on a `v1.0.0` release :+1:
