### ISSUE TITLE
Support configurable lint sources for LintCertificate

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#344]
In https://github.com/zmap/zlint/pull/337 we split lints into directories by category. We should follow up on this change by implementing a breaking API change that will allow consumers to provide an options struct to the top level `zlint.LintCertificate` function that allows choosing lint categories/sources to use to lint the certificate.

We will also need to decide on default lint categories. My current preference is to match the existing ZLint behaviour and run **all** categories unless otherwise specified but I could be convinced if folks think just the RFC or CABF categories should be used by default.

**Comment by cpu** [comment]
I've assigned myself this issue but may not have a chance to submit a PR for a little bit. If someone else is eager to take this let me know and I'll re-assign.

**Comment by cardonator** [comment]
Personally, I agree with running all categories by default unless otherwise specified. Also, does it make sense to have include _and_ exclude category capability? (I'm specifically thinking of ETSI here where you might want to "run everything except ETSI".

**Comment by cpu** [comment]
> Also, does it make sense to have include and exclude category capability? 

That sounds nice :+1:

**Comment by cpu** [comment]
> My current preference is to match the existing ZLint behaviour and run all categories unless otherwise specified but I could be convinced if folks think just the RFC or CABF categories should be used by default.

Chatting about this more with @zakird I'm open to the idea of defaulting to all lint sources just for CI and having the library offer a more conservative default (that's his preference). I'm primarily worried about bit rot in CI if there are lint categories that aren't exercised during integration tests.

**Comment by timfromdigicert** [comment]
If everything is run by default, and you get something you don't like, you can turn that off.

If everything isn't run by default, and you don't get something you needed, you're guaranteed not to notice.

**Comment by weddi-eddy** [comment]
It'd be really cool to have a switch to be able to select what you want. By default, I'd say it does everything (which, perhaps there's a switch that simply lists the folders and can also list the lints in each folder; something like zlint --list-folders or something).  If you run zlint as per normal, it does the default folders, whatever is considered to be default.  If you want specifics, then you can add a switch that allows you to select the folders based on the results from the --list-folders switch I suggest above.

zlint --only-folders cabf,mozilla,ev

That would be easy on any scripts that are run and the same logic can be used for API.

**Comment by weddi-eddy** [comment]
Thinking on this a bit more, I think there should be a way of easily telling what is included by default (for sanity's sake) so you know what ZLint is polling against.

**Comment by zakird** [comment]
Quick note, I would strongly prefer this to be based on ZLint Source not directory.

**Comment by cardonator** [comment]
I agree, I'd prefer it to be based on source.

**Comment by weddi-eddy** [comment]
Sure! I say directory but realistically, I just like the idea of switches as it can be easily scripted. Source is fine.

**Comment by cpu** [comment]
Yup, agreed on the folders front (I avoided the term in my issue desc). The folder is a source level construct associated with [the package](https://golang.org/doc/code.html#Organization) and is compiled away. It's something contributing developers should be concerned with but not consumers of the API or the `zlint` command line.

Otherwise the idea to be able to enumerate the available sources programmatically for library consumers and via a command line flag for `zlint` binary users makes sense to me.

**Comment by cpu** [comment]
> I've assigned myself this issue but may not have a chance to submit a PR for a little bit (~a week?). If someone else is eager to take this let me know and I'll re-assign.

I decided to prioritize landing the Mozilla lints that have been in the PR queue for a long time w/ #353. I'll return to this once as much of that code as can be landed is in master.

**Comment by cpu** [comment]
I started working on this feature. I'm going to try and break it up across a handful of PRs. The first of which (likely the largest by diff size) is ready for review: https://github.com/zmap/zlint/pull/364

**Comment by cpu** [comment]
I made some progress on this today and have [a mostly complete implementation branch](https://github.com/cpu/zlint/tree/cpu-refactors-lint-registration) ([WIP Diff here](https://github.com/zmap/zlint/compare/master...cpu:cpu-refactors-lint-registration?expand=1)).

I still need to do a cleanup pass, add some missing unit test coverage, and update documentation. Everything in there is subject to change but probably close to what we'll land on ultimately.

**Comment by cpu** [comment]
My PR with the library/CLI updates is ready for review: https://github.com/zmap/zlint/pull/372

**Comment by cpu** [comment]
I'd encourage the folks that were interested in this functionality to test the [v2.0.0 release candidate](https://github.com/zmap/zlint/releases/tag/v2.0.0-rc1) that is now available. It includes the implementation of including/excluding lints by source (7741587) and lots of other treats (binary `zlint` cmd releases!).

I'll be working on smoke testing an integration with CFSSL ahead of pushing a finalized v2.0.0 release.

Cc @cardonator @weddi-eddy
