### ISSUE TITLE
[Question] - Including and Excluding Folders

### ISSUE THREAD

**Issue by weddi-eddy** [zmap/zlint#350]
Hello.  This is a question I was wondering based on comments in pull 336.

How can we include or exclude lints from various folders? Is there an easy way to do this?  Let's say I have a bunch of CAs in a picnic basket that only need to conform to one or a select few Lint folders.  How can I set ZLint to only check the folders (and lints within the folders) of what I want?

**Comment by cpu** [comment]
:wave: hi @weddi-eddy. Thanks for the question,

> How can we include or exclude lints from various folders? Is there an easy way to do this?

There isn't a way to do this presently without modifying the ZLint source (e.g. to omit the `RegisterLint` calls from the lints you don't want run). You'll want to track this issue for an update to the linting API that would allow specifying categories to include/exclude: https://github.com/zmap/zlint/issues/344

I'm going to close this issue to keep the discussion centralized on #344.
