### ISSUE TITLE
explicitText lint description and semantics differ from RFC 5280

### ISSUE THREAD

**Issue by jsha** [zmap/zlint#369]
The description of explicitText in https://github.com/zmap/zlint/blob/e3ad0f9eba10b1fa0ee70e6581a627cdfeaa590c/lints/rfc/lint_ext_cert_policy_explicit_text_not_utf8.go#L17-L28

Differs from [RFC 5280 page 33](https://tools.ietf.org/html/rfc5280#page-33):

> An explicitText field includes the textual statement directly in
> the certificate.  The explicitText field is a string with a
> maximum size of 200 characters.  **Conforming CAs SHOULD use the
> UTF8String encoding for explicitText, but MAY use IA5String.
> Conforming CAs MUST NOT encode explicitText as VisibleString or
> BMPString.**  The explicitText string SHOULD NOT include any control
> characters (e.g., U+0000 to U+001F and U+007F to U+009F).  When
> the UTF8String encoding is used, all character sequences SHOULD be
> normalized according to Unicode normalization form C (NFC) [NFC].

I've emphasized the section that differs. I used Google to try and find the source of the language that's currently quoted in the lint, and it appears to be from https://tools.ietf.org/html/draft-cooper-pkix-rfc5280-clarifications-00#section-2, a clarification draft that never made it past Internet Draft status.

I think we should probably revise the lint to quote RFC 5280 instead, and should also revise what the lint is actually checking. However, if that's too disruptive for the reasons laid out in draft-cooper-pkix-rfc5280-clarifications, we should revise the comment in this lint to make it clear what document it's quoting and why.

**Comment by sleevi** [comment]
@jsha https://tools.ietf.org/html/rfc6818#section-3 ?

**Comment by jsha** [comment]
Ah, thanks. I missed that one. I'll send a PR to add that reference to the lint comment.

**Comment by zakird** [comment]
Is this resolved? (I think it is, but not 100% and don't want to inappropriately close)

**Comment by cpu** [comment]
It looks like the RFC ref'd by sleevi did make it into a comment in-file:
https://github.com/zmap/zlint/blob/fd40f579253ea1ebfb18a585ab5cd8e7dcde61aa/v2/lints/rfc/lint_ext_cert_policy_explicit_text_not_utf8.go#L17-L30

I'm going to go ahead and close this issue. Thanks!
