### ISSUE TITLE
Cleanup: Move the lint initialization to be the start of a file

### ISSUE THREAD

**Issue by sleevi** [zmap/zlint#371]
This came up in #369 , and then expanded upon in #370 .

The current style of lints is that they follow a form of
* `citation of relevant spec` (usually)
* `Lint.Initialize`
* `Lint.CheckApplies`
* `Lint.Execute`
* `init()`

The citation of the relevant spec text is related to the `Citation` and `Source` within the new `Lint`, but that's not immediately clear, especially for `Lint`s that have sizable quotations or implementations.

One suggestion from #370 was to consider moving the `init()` function to the start of the file, so that opening a file, it's possible to read what's being checked, where the requirement comes from, and only after that, how that particular check is implemented.

**Comment by cpu** [comment]
I think we can call this done now thanks to @robplee :tada:

I mentioned in [a comment](https://github.com/zmap/zlint/pull/536#issuecomment-762361695) but if someone were interested it would be nice to follow-up on this with a CI lint that checks that the lint init function appears at the start of the file. Some kind of programmatic backstop to prevent us from forgetting it during code review :-)
