### ISSUE TITLE
Linting CRL and OCSP responses

### ISSUE THREAD

**Issue by jsha** [zmap/zlint#382]
Hi all,

I think it would be useful to have linters for CRL and OCSP responses. Do you think that would be a good addition to this repo, or do those make sense as a separate tool?

Thanks,
Jacob

**Comment by cpu** [comment]
Personally I think it makes sense to include in-repo :+1: 

I suspect it might make be a good idea to make a separate command line tool (vs adding to `cmd/zlint/main.go`) for linting these other resource types from the CLI (if only to avoid piling in extra command line flags).

**Comment by zakird** [comment]
I agree this makes sense. Similar to @cpu, I'd like to make sure it doesn't greatly complicate the existing code base.

**Comment by jsha** [comment]
I realized I opened this issue twice; sorry about that! Closing in favor of #458, which has a reference for a potentially good set of lints to implement.
