### ISSUE TITLE
breaking change: rename exported lint.AppleCTPolicy constant

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#418]
The `lint.AppleCTPolicy` constant has a generic value ("Apple") but the constant name itself is too specific "CT Policy": https://github.com/zmap/zlint/blob/b28794baf37819442e98e28655a8d4536681b095/v2/lint/source.go#L35

That was fine for the v2.0.0 release because there was only one lint in `lints/apple/` using the source, and it is CT specific. Now that we're adding more Apple policy lints (e.g. #417) we need a better solution.

Since this is an exported var we can't rename it (or change the value) without it being a breaking change. We could introduce a second "lint.ApplePolicy" constant, but if it had the same generic value there will be trouble unmarshaling.

Likely the best solution is to rip the bandaid off and just rename the constant from `lint.AppleCTPolicy` to `lint.ApplePolicy` and bump the major version again. Since that's a fair amount of work I'm filing this as an issue to save for when we have more breaking changes to make.

**Comment by zakird** [comment]
Agree, we should "just do it" and do it sooner rather than later. _sigh_.

**Comment by cpu** [comment]
> Agree, we should "just do it" and do it sooner rather than later. sigh.

Wellllllllll.... sooner turned into later anyway :-) BUT we have [a better reason](https://github.com/zmap/zlint/pull/493) to cut a major release so we might as well knock this out at the same time.

I assigned this to myself and will try to land a PR shortly.

**Comment by cpu** [comment]
PR up: #501
