### ISSUE TITLE
Bug: .onion names are no longer prohibited by the Baseline Requirements

### ISSUE THREAD

**Issue by sleevi** [zmap/zlint#440]
[`lint_san_dns_name_onion_not_ev_cert.go`](https://github.com/zmap/zlint/blob/fd40f579253ea1ebfb18a585ab5cd8e7dcde61aa/v2/lints/cabf_br/lint_san_dns_name_onion_not_ev_cert.go) has a lint that returns an error if a `.onion` name appears in the SAN and the certificate is not EV.

However, as of BRs [1.6.9](https://cabforum.org/2020/02/20/ballot-sc27v3-version-3-onion-certificates/), with the adoption of [CA/Browser Forum Ballot SC27v3](https://cabforum.org/2020/02/20/ballot-sc27v3-version-3-onion-certificates/), `.onion` names are now permitted in BR certificates, provided they are subject to additional constraints (differing from the EV Guidelines)

The following tasks are needed:
* Either Lints can be expanded to support a `RetiredDate` that is similar to their [`EffectiveDate`](https://github.com/zmap/zlint/blob/99579098a16c10d1d704b8b8149dd8c35329107f/v2/lint/base.go#L59-L62), or the EV-only lint be retired to 2020-03-27, the effective date they became permitted by the BRs
  * The effective date may need to be modified, such that it ensures that prior to the effective date, no `.onion` cert existed (EV or BRs) - that is, it should have been revoked.
  * While if issued after the effective date, but before the retired date, it should be EV.
* A new lint, for the BRs, to ensure that the label preceeding the `.onion` address is a:
  > "valid Version 3 Onion Address, as defined in section 6 of the Tor Rendezvous Specification - Version 3 located at https://spec.torproject.org/rend-spec-v3"
  as per the BRs, v1.6.9, Appendix C
  * The effective date for this lint would be 2020-03-27

**Comment by cpu** [comment]
> Either Lints can be expanded to support a RetiredDate that is similar to their EffectiveDate, or the EV-only lint be retired to 2020-03-27

@sleevi Since this is the first time this has popped up within ZLint (_as far as I know_) I think I would prefer we update `lint_san_dns_name_onion_not_ev_cert.go`'s `checkApplies` to check whether the `NotBefore` is after `2020-03-27`. I think we can defer adding a more generalized `RetiredDate` that way. WDYT? I can't personally commit to implementing much right now and bias towards smaller fixes for the short-term.

**Comment by sleevi** [comment]
@cpu Yeah, entirely reasonable! There were definitely lots of ways to solve this, and I wasn’t sure the preference. For example, I wasn’t sure if just making this a “check for rules of .onion” instead (handling both the EV and the DV rules in one lint) made sense.

My assumption was that we should try to separate out lints when EVG and BRGs have separate requirements, or when there are separate dates. Does that match your understanding?

**Comment by cpu** [comment]
> My assumption was that we should try to separate out lints when EVG and BRGs have separate requirements, or when there are separate dates. Does that match your understanding?

Yup, that sounds ideal to me :+1: Thanks for thinking this through!

**Comment by cpu** [comment]
>  I split the new lint out (for v2/v3 .onion name well-formedness)

Landed in d4acbba :tada:
