### ISSUE TITLE
LINT for the correlation between EKU and KU

### ISSUE THREAD

**Issue by RufusJWB** [zmap/zlint#473]
I couldn't find a LINT for the correlation between EKU and KU as described in [RFC5280 4.2.1.12](https://tools.ietf.org/html/rfc5280#section-4.2.1.12) . Is there one? If not, we should implement one according this spec:

>  If a certificate contains both a key usage extension and an extended
>    key usage extension, then both extensions MUST be processed
>    independently and the certificate MUST only be used for a purpose
>    consistent with both extensions.  If there is no purpose consistent
>    with both extensions, then the certificate MUST NOT be used for any
>    purpose.
> 
>    The following key usage purposes are defined:
> 
>    anyExtendedKeyUsage OBJECT IDENTIFIER ::= { id-ce-extKeyUsage 0 }
> 
>    id-kp OBJECT IDENTIFIER ::= { id-pkix 3 }
> 
>    id-kp-serverAuth             OBJECT IDENTIFIER ::= { id-kp 1 }
>    -- TLS WWW server authentication
>    -- Key usage bits that may be consistent: digitalSignature,
>    -- keyEncipherment or keyAgreement
> 
>    id-kp-clientAuth             OBJECT IDENTIFIER ::= { id-kp 2 }
>    -- TLS WWW client authentication
>    -- Key usage bits that may be consistent: digitalSignature
>    -- and/or keyAgreement
> 
>    id-kp-codeSigning             OBJECT IDENTIFIER ::= { id-kp 3 }
>    -- Signing of downloadable executable code
>    -- Key usage bits that may be consistent: digitalSignature
> 
>    id-kp-emailProtection         OBJECT IDENTIFIER ::= { id-kp 4 }
>    -- Email protection
>    -- Key usage bits that may be consistent: digitalSignature,
>    -- nonRepudiation, and/or (keyEncipherment or keyAgreement)
> 
>    id-kp-timeStamping            OBJECT IDENTIFIER ::= { id-kp 8 }
>    -- Binding the hash of an object to a time
>    -- Key usage bits that may be consistent: digitalSignature
>    -- and/or nonRepudiation
> 
>    id-kp-OCSPSigning            OBJECT IDENTIFIER ::= { id-kp 9 }
>    -- Signing OCSP responses
>    -- Key usage bits that may be consistent: digitalSignature
>    -- and/or nonRepudiation
>

**Comment by cpu** [comment]
This was addressed by #497 and I've opened a separate issue for some follow-up discussion: https://github.com/zmap/zlint/issues/553
