### ISSUE TITLE
Cut v3.0.0 release.

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#503]
We have two changes in master that break backwards compat. and require a major version bump from v2.x.x to v3.0.0:

* [x] - https://github.com/zmap/zlint/pull/493 - changed lint results/names
* [x] -https://github.com/zmap/zlint/pull/501 - renamed an exported constant

There's one more lint change we should try to land at the same time that I'm currently considering a soft blocker:

* [x] - https://github.com/zmap/zlint/issues/496 - split up a lint with multiple finding levels.

Zakir also suggested a breaking change to the lint sources:

* [x] - combine `lint.ZLint` and `lint.AWSLabs` lint sources into `lint.Community`

Lastly I'd like to see us cut over to Github Actions before making this release so that I can test the Goreleaser integration with the Github workflow:

* [x] - https://github.com/zmap/zlint/issues/500- switch to Github Actions 

If there are other changes/bugs that folks want to see resolved before a v3.0.0 release please list them in the comments and I will update this issue description.

Once we have these changes done we should cut a v3.0.0 release, taking care to pay attention to the Go modules requirements for versioning (e.g. creating a new `v3/` subdirectory and moving all of the code over).

**Comment by RufusJWB** [comment]
I'm not sure if I forgot to press the comment button or if my comment was deleted. If the latter, please excuse me for posting again.

Do you think you could include #490 and #491 in this release?

**Comment by cpu** [comment]
Hi @RufusJWB,

> I'm not sure if I forgot to press the comment button or if my comment was deleted. If the latter, please excuse me for posting again.

I think you posted the comment on #490 [by mistake](https://github.com/zmap/zlint/pull/490#issuecomment-733219591) and I missed it there. Thanks for reposting!

> Do you think you could include #490 and #491 in this release?

I can't speak for the other maintainers but I'm a bit underwater right now with work responsibilities and don't expect I will have the energy to review these PRs this week. I think given that neither have an approval stamp yet it might be better to cut a v3.0.1 release shortly afterwards when they are ready.

Apologies for the delays getting those reviewed. I think there's someone starting a contract position to help support ZLint in the near future and I'm hopeful that will make reviews happen with a better cadence.

**Comment by RufusJWB** [comment]
@cpu Maybe you could include #490 since this one is straight forward. #491 is more complex to review.

**Comment by zakird** [comment]
As @cpu mentioned, we have additional help coming to get these reviewed and merged. 🤞 this will be in place next week. Given that neither #490 nor #491 have breaking changes that require a major release, I think it's fine to release without them, and we'll get a minor revision out as soon as they're in. Longterm, we'll be better off having regular updates going out than gating releases on pending issues.

**Comment by cpu** [comment]
I added the Travis -> Github workflows switch as a task for the V3 release. I'd like to use this as an opportunity to make sure the Github Action workflow for Goreleaser works as expected. I assigned myself this release issue to make sure I'm the one that suffers the debugging if there are problems.

If we can get both #506 and #505 merged over the next few days I'll start on the V3 release.

**Comment by zakird** [comment]
Not at a computer, but will review both by EOD.

**Comment by cpu** [comment]
I'm working on a dry run of a v3 release with some test repos to make sure I have a handle on what I'm doing before I pull the trigger here.

At a high level my plan is:
* copy everything in `v2/` to `v3/`
* update all of the import paths and references (especially CI action working directories).
* delete the old `v2` directory.
* open a PR with all the above, merge to master after review.
* cut a v3.0.0-RC1 tag with HEAD of master, push it through the automation.
* ???
* profit.

cc @dadrian - Does this mesh with your understanding of Go module major version bumps when you don't want to support both major versions simultaneously?

**Comment by dadrian** [comment]
@cpu Sounds correct to me.

**Comment by cpu** [comment]
@dadrian Thanks for double checking my logic.

> I'm working on a dry run of a v3 release with some test repos to make sure I have a handle on what I'm doing before I pull the trigger here.

I tried this plan with a fork of ZLint and ZCertificate and it worked the way you would hope. The ZCertificate fork that depended on the V2 version of the ZLint fork continued to work as expected when the v2 directory of the ZLint fork was deleted in master.

I feel confident enough to move forward with the v3.0.0-rc1 PR + tag here.

**Comment by cpu** [comment]
I've cut [a release candidate tag for v3.0.0](https://github.com/zmap/zlint/releases/tag/v3.0.0-rc1) and opened a [call for testing](https://github.com/zmap/zlint/issues/511) issue.

The new Github Action based Go Releaser flow worked perfectly. One nice bonus: we can deprecate the [zlintbot](github.com/zlintbot) account since GIthub uses its own token to upload the release now. I've gone ahead and removed @zlintbot's write access to the repo :tada: Once we've completed https://github.com/zmap/zlint/issues/507 it should be possible to do the same for @tld-update-bot.

I'm going to close this issue out and we can track any further required work on #511. Thanks everyone.

**Comment by zakird** [comment]
Thanks @cpu for pulling this together!!
