### ISSUE TITLE
Call for testing: ZLint 3.0.0 release candidate

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#511]
:wave: Hi folks,

I've cut a new **major** release candidate, [v3.0.0-rc1](https://github.com/zmap/zlint/releases/tag/v3.0.0-rc1). Please see the release notes for the list of breaking changes & the full changelog.

Testing would be appreciated. If you find any problems feel free to report them in this issue. I will plan to cut a final v3.0.0 release in the next week or so if no problems are identified, per the ["Versioning and Releases"](https://github.com/zmap/zlint#versioning-and-releases) guidance in the README.

**Comment by cpu** [comment]
How do folks feel about including lints in a final release that weren't in the RC? E.g. https://github.com/zmap/zlint/commit/1eb11ce3552704904404d56a65f4be3511828dbf which landed just now.

My gut instinct is to try and stay faithful to the RC and only include subsequent bug fixes or data updates (if any) in the final tag. Does that square up with the community/other maintainers views on the matter?

**Comment by zakird** [comment]
I agree don't add any new lints. Should be relatively stable now. We can
release 3.1.0 soon enough.

**Comment by cpu** [comment]
Sounds good. I'll try to push a v3.0.0 tag in the next few days.

**Comment by cpu** [comment]
The final v3.0.0 release is now published: https://github.com/zmap/zlint/releases/tag/v3.0.0
