### ISSUE TITLE
feature request: ZLint command line -version flag

### ISSUE THREAD

**Issue by weddi-eddy** [zmap/zlint#519]
I see that v3 was released recently. I just did an update from what I believe is v2 to v3. Is there an easy way to tell the update was successful and which version I am running?  I think a -version switch would be really useful.

**Comment by cpu** [comment]
:wave: Hi @weddi-eddy 

> I see that v3 was released recently.

Not quite yet, just a release candidate. We should have a final v3.0.0 release uploaded in the next few days.

> I think a -version switch would be really useful.

This seems like a reasonable feature request for the `zlint` cli 👍

**Comment by cpu** [comment]
> Not quite yet, just a release candidate. We should have a final v3.0.0 release uploaded in the next few days.

This has been published now: https://github.com/zmap/zlint/releases/tag/v3.0.0

> Is there an easy way to tell the update was successful and which version I am running?

@weddi-eddy Until there's a `-version` flag the easiest way is probably to download the binary release for your platform from the release page's assets. E.g. https://github.com/zmap/zlint/releases/download/v3.0.0/zlint_3.0.0_Linux_x86_64.tar.gz for 64bit Linux. Running the `zlint` binary from the release archive will guarantee you're using the right version :-)

**Comment by cpu** [comment]
There's a new `-version` flag for both `zlint` and `zlint-gtld-update` as of c47eab4 that will appear in the next release.

In the meantime I noticed that the `--help` output from existing release binaries includes the release version. You can use that as a work-around for previous releases (I tested with both 3.0.0 and 3.1.0 but I believe this was implemented from the start of publishing binaries).
