### ISSUE TITLE
Lint that DSA is not used 

### ISSUE THREAD

**Issue by sleevi** [zmap/zlint#537]
DSA was part of the BRs up to [version 1.7.1](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.1.pdf) (2020-08-20), where it was removed as part of the [browser alignment ballot](https://cabforum.org/2020/07/16/ballot-sc31-browser-alignment/).

The source of the "lack of DSA" goes back to [Mozilla Policy 2.0](https://wiki.mozilla.org/CA:CertMaintenancePolicyV2.0), which did not list DSA as acceptable/supported (effective 2011-02-02). However, the question of "absence or violation" was not resolved until [Policy 2.4.1](https://github.com/mozilla/pkipolicy/blob/2.4.1/rootstore/policy.md), effective date 2017-03-31, in which it was restructured to clarify that it's an exclusive set of algorithms.

Zlint has `cabf_br/lint_dh_params_missing.go`, to ensure DH params are present for DSA certificates, but that lint is obviated by BRs 1.7.1, and may itself be supplanted by an additional Mozilla-specific lint on DSA prohibition set for the 2.4.1 effective date.

**Comment by sleevi** [comment]
Marking it as "question" so people can offer their interpretation of the effective dates here, should a lint be contributed.

**Comment by sleevi** [comment]
This also requires updating `cabf_br/lint_public_key_type_not_allowed`

**Comment by robplee** [comment]
Question: a number of lints are going to be deprecated/rendered worthless by a new "lint_no_more_dsa" check.  Should we also create an issue to remove them now or do we want to wait until this has been completed?  I guess the other question I have, as a new contributor, is to ask if removing said lints lints will necessitate a major version number increase?

Apologies if this is the wrong place to ask.

**Comment by sleevi** [comment]
@robplee It’s a good question! I mentioned the effective dates, precisely because it is example of something that once was allowed, but no longer. In other cases, such as certificate lifetimes, lints have added new restrictions (e.g. 825 days to 398), but we’ve kept the old lint around to cover the period in which it was allowed. So introducing a “no DSA allowed” would have an effective date `Y`, as mentioned above, while the other DSA tests would cover `X...Y`.

That’s at least how things have been done, but as a result, it does mean things are additive over time, which might make things less sustainable, which is also why I tagged it discussion.

Removing lints would generally be a new major version, yes.

**Comment by zakird** [comment]
I don't know if we necessarily want to remove old lints immediately because this prevents longitudinal analysis. Rather than remove altogether, we may want to move these into a new archive bin that doesn't run by default. For example, sometimes at Censys, we re-lint _all_ certificates in the store to help patch up errors that leak through from ZLint bugs. I don't think we'd want to lose the historical data about certificates when we re-run.

**Comment by zakird** [comment]
We could also add an optional "stopped being effective at" date to lints similar to what we do with TLDs. In that case, we could leave the lint in-place and simply update that date. I think I might prefer this offhand.

**Comment by cpu** [comment]
> I think I might prefer this offhand.

I'll have to read this thread in detail when I'm not between meetings but my first instinct is that this would be my preference too.

**Comment by sleevi** [comment]
Yeah, I could swear that came up in a review discussion somewhere, but I'm having trouble finding it, but SGTM.

**Comment by cardonator** [comment]
I like the idea of stopped being effective... what about superseded?

**Comment by christopher-henderson** [comment]
Merged in with #572. #574and #575  were fired up for the BR version of this as well as keeping the discussion alive for sunset dates and superseding lints (respectively).
