### ISSUE TITLE
CAB BRGs validity period 397/8 days

### ISSUE THREAD

**Issue by RufusJWB** [zmap/zlint#552]
We should move the lints https://github.com/zmap/zlint/blob/master/v3/lints/apple/lint_w_server_cert_valid_time_longer_than_397_days.go and https://github.com/zmap/zlint/blob/master/v3/lints/apple/lint_e_server_cert_valid_time_longer_than_398_days.go to the CAB_BRG folder, since they were adopted to the BRGs with release 1.7.1

**Comment by sleevi** [comment]
I think this is a dupe of https://github.com/zmap/zlint/issues/539 ?

**Comment by RufusJWB** [comment]
oh yes, indeed
