### ISSUE TITLE
Introduce an upper bounds to effective dates

### ISSUE THREAD

**Issue by christopher-henderson** [zmap/zlint#575]
In the issue for [`Lint that DSA is not used `](https://github.com/zmap/zlint/issues/537#issuecomment-757876869) we opened up the idea of a policy that may eventually be deprecated, and the notion of a sort of `notAfter` for lints was introduced.

One would think this change would be as simple as

```go
// Lints automatically returns NE for all certificates where CheckApplies() is
// true but with NotBefore < EffectiveDate. This check is bypassed if
// EffectiveDate is zero.
EffectiveDate time.Time `json:"-"`
// Lints automatically returns NE for all certificates where CheckApplies() is
// true but with NotBefore > IneffectiveDate. This check is bypassed if
// IneffectiveDate is zero.
IneffectiveDate time.Time `json:"-"`
```

...with the consequent updates to the framework and documentation. I don't think I see any reason why any extant lint would need a code change to accommodate something like this.

@zakird @cpu @sleevi and @robplee seemed to be the interested parties here.

**Comment by christopher-henderson** [comment]
There was also a discussion brought up by @cardonator on the possibility of encoding the notion of a lint being "superseded". One could imagine something like...

```go
&lint.Lint {
    ...
    // In case multiple policies can supersede this one?
    SupersededBy []lint.Lint
    ...
}
```

...although if it is always the case that once one policy supersedes another, that the first would acquire an `IneffectiveDate` and this case would naturally be handled? Or do we policies that are technically both alive on intersecting dates, but one overrides the other if both applied?

**Comment by dadrian** [comment]
I wouldn't add `SupersedesBy` until it's actually a problem. 

> Or do we policies that are technically both alive on intersecting dates, but one overrides the other if both applied?

This can also be solved by writing a single lint with an if statement in the middle.

**Comment by zakird** [comment]
I don't think that's necessarily true. The two pints could have different
citations, names, scopes.

I'm not opposed to having a date when a lint is no longer applicable. If we
have an effective date, it seems quite reasonable to have an end date too.

In terms of superseded, I'm not sure if that specific piece is worth
codifiying. We've tried really hard to have lints be simple and
independent. Are there cases like this where there are conflicting
requirements that both apply on the same date? Offhand, that sounds like a
problem that should be resolved in a policy document.

**Comment by dadrian** [comment]
To be clear, I think a `NotAfter` / `IneffectiveDate` is totally reasonable. 🚀

**Comment by cardonator** [comment]
FWIW I don't have a use case where Superseded would be helpful, it was just something I thought we ought to consider when adding boundaries. IOW if it did have any use case.

**Comment by christopher-henderson** [comment]
> We've tried really hard to have lints be simple and independent.

Precisely. And this would be, essentially, building a statically defined graph structure implicitly in code which screams "complications".

Given that we don't have a use case immediately I kinda doubt that we would want to do it.

...But at the same time I can't help but noodle on how it would be done if we did :stuck_out_tongue: (interesting problems are...interesting :man_shrugging: ) perhaps something like a single `supersedes.txt` which defines the structure so that individual lints could otherwise be oblivious to it.
