### ISSUE TITLE
Support for linting profiles

### ISSUE THREAD

**Issue by christopher-henderson** [zmap/zlint#594]
Conversations in #583 led us down the path of the concept of a `profile` in ZLint.

A profile is a named grouping of lints that, taken together, refer to a published source that enumerates and names requirements into one, larger, requirement.

A profile _must_ come from a publicly published source and _should_ have a citation explaining why these requirements are grouped together.

#### Why not just use `excludeNames/includeNames`?
1. The intent of profiles is _not_ born of convenience.
    * That is, If individual operators wish to run arbitrary, privately published, groupings of lints then that is what `excludeNames/includeNames` are still for.
2. The intent is for profiles to be sourced from publically published requirements.
3. CAs will want to target these published profiles.
4. However, finding and grouping the correct lints together that match a given profile may not be trivial.
5. We would like for not every CA to have to replicate the same, magical, `excludeNames/includeNames` that correctly identifies the aforementioned profile.

**Comment by cpu** [comment]
@christopher-henderson Can you write something in the issue body? I appreciate the desire to link PRs to issues but if the issues are blank it's maybe a net neutral act :-)

**Comment by christopher-henderson** [comment]
Sorry @cpu in my rush last weekend I neglected to fill this ticket out with anything meaningufl :pray:
