### ISSUE TITLE
Cut v3.2.0 release candidate

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#605]
It's been a little while since we've had a release and we intend to make some breaking changes soon to remove ETSI lints.

Scanning the [diff between v3.1.0 and master](https://github.com/zmap/zlint/compare/v3.1.0...master) I think the changes justify a `minor` release. I don't see anything that merits a `major` release bump. Here''s my quick summary:

* zcrypto updates (`ea3fdbd5ea2`)
* gtld updates (2021-04-22)
* Switched project to Go 1.16
* Added `-version` flag to `zlint`/`zlint-gtld-update`.
* Support for lint `IneffectiveDate` to complement `EffectiveDate`.
* Misc typo fixes.
* RFC lint updates:
  * Fixed `e_serial_number_not_positive` to forbid zero.
  * Fixed `e_subject_given_name_max_length` boundary.
  * Fixed `e_subject_surname_max_length` boundary.
  * Added `w_subject_given_name_recommended_max_length` lint.
* Mozilla lint updates:
  * Added lint `e_prohibit_dsa_usage` effective as of March 31st, 2017.
* CABF_BR lint updates:
  * Changed lint `e_dsa_params_missing`, ineffective as of August 20th, 2020.
  * Added lint `e_br_prohibit_dsa_usage` effective as of August 20th, 2020.
* Updates for contributors:
  * cert generation resources.
  * static analysis for lint function ordering.

**Comment by cpu** [comment]
Things that might be nice to try and have addressed for this release:
* #593 (needs an existing lint tweaked slightly and a new lint split off)
* #601 (blocked on MDSP discussion)

**Comment by cpu** [comment]
We'll save linting profiles (in review) + removing ETSI lints for a near-future v4.0.0.

**Comment by christopher-henderson** [comment]
Cut the RC to https://github.com/zmap/zlint/releases/tag/v3.2.0-rc1 and shot out the call for testing.

**Comment by aarongable** [comment]
LE/ISRG has tested and everything seems good on our end: https://github.com/letsencrypt/boulder/pull/5442

**Comment by christopher-henderson** [comment]
Thank you @aarongable!

Seemed reasonably move forward and cut [v3.2.0](https://github.com/zmap/zlint/releases/tag/v3.2.0).

**Comment by cpu** [comment]
Thanks @christopher-henderson !
