### ISSUE TITLE
move lint mp_allowed_eku to cabf_br folder

### ISSUE THREAD

**Issue by orangepizza** [zmap/zlint#612]
as ballet SC31 merged this requirement into CA/B BR as 7.1.2.2, it's be better move this lint there too.
https://github.com/cabforum/servercert/commit/6b870f92d4788a52c2bbc9d96a1db17751e906b1
, from BR line 1619

**Comment by sleevi** [comment]
Thanks for reporting this!

Closing, as #539 tracks this work :)
