### ISSUE TITLE
Test certificate generator doesn't create a certificate chain

### ISSUE THREAD

**Issue by robplee** [zmap/zlint#620]
In #569, @christopher-henderson added a helpful tool for generating certificates and chains.  However, it currently contains a bug in that the certificate chain produced is a chain in name only and not cryptographically as all the certs are self-signed.

This means that the script always has to be hacked a bit to generate certificates which don't return true on util.SelfSigned(), this came up in the course of generating the test data for #613 which needed an intermediate cert for which util.IsCACert() would return true but for which util.IsRootCert would return false.

Therefore, I think it would be worthwhile to fix the various newThing functions to take the signing key as an argument (for newIntermediate and newLeaf) and return the key included in the certificate created by the function so it can be passed on to the next function call.

If this issue sounds like something which should be addressed then I'm happy to work on it myself.

**Comment by christopher-henderson** [comment]
@robplee I'll look at. It _should_ be generating a self signed trust anchor and then chaining that down appropriately. But it could have a bug in it, yeah.

**Comment by robplee** [comment]
So, the previous cert is passed in as the parent certificate to the call to CreateCertificate but then the private key used in the call to CreateCertificate is that of the key pair generated in the function and it's that key, priv, which is used to sign according to https://pkg.go.dev/crypto/x509#CreateCertificate

**Comment by christopher-henderson** [comment]
Argggh good catch @robplee. I'll fix it up this weekend :metal: 

![image](https://user-images.githubusercontent.com/8518514/126011268-2e87efab-9be0-4d43-8f41-dae1b1c39a6d.png)
