### ISSUE TITLE
Can we cut a new release?

### ISSUE THREAD

**Issue by cardonator** [zmap/zlint#668]
There have been multiple TLD updates since the last release of zlint. Can we cut a new release to stay up to date with these?

**Comment by christopher-henderson** [comment]
Ah, sure @cardonator. There were a handful of key features that have been stuck in limbo that I wanted to get in, but the TLDs are good enough to update on.

**Comment by christopher-henderson** [comment]
Release candidate up at https://github.com/zmap/zlint/releases/tag/v3.3.1-rc1

**Comment by cpu** [comment]
If TLD updates are the impetus for a release https://github.com/zmap/zcrypto/pull/320 needs to be merged and zlint updated to use it.

**Comment by christopher-henderson** [comment]
#670 is up which pulls in [zcrypto@599ec18ecbac3129a5ed383d15188060229b500d](https://github.com/zmap/zcrypto/commit/599ec18ecbac3129a5ed383d15188060229b500d) which includes https://github.com/zmap/zcrypto/pull/320

**Comment by christopher-henderson** [comment]
[v3.3.1](https://github.com/zmap/zlint/releases/tag/v3.3.1) has been release.
