### ISSUE TITLE
Add close-primes detection via Fermat's factorization

### ISSUE THREAD

**Issue by vanbroup** [zmap/zlint#673]
zlint is currently missing a close-primes lint, maybe we can repurpose the check from boulder for this?

https://github.com/letsencrypt/boulder/commit/89000bd61cfc6f373cb48b6f046d4fce7df5468e

https://fermatattack.secvuln.info/

cc: @aarongable

**Comment by aarongable** [comment]
Happy for the boulder implementation to be reused for this, but I don't currently have time to put together the zlint PR myself, sorry!

**Comment by vanbroup** [comment]
No problem, thanks for letting this code be used. I can work on this in a few weeks (currently on vacation).

**Comment by christopher-henderson** [comment]
@aarongable @vanbroup the change listed in Boulder is reasonably contained (and commented) so I can take a crack at this. Although, I may enlist Aaron (or at least @ mention them) in the PR for a smoke check

**Comment by aarongable** [comment]
Should this bug be considered fixed/closed, or is there more work to do now that #674 has been merged?
