### ISSUE TITLE
Placeholder Discussion for JZLint

### ISSUE THREAD

**Issue by christopher-henderson** [zmap/zlint#709]

**Comment by mtgag** [comment]
There is a port of zlint in Java, called jzlint. See: https://github.com/MTG-AG/jzlint. Not all zlint lints are yet implemented. Also some additional lints exist starting to cover other specifications (see e.g. #710) or lint of OCSP responses. During the port we identified a few positions in zlint (or jzlint) that may need minor refactoring. @christopher-henderson created this issue to keep track of the conversation.

**Comment by mtgag** [comment]
Maybe the best way to start on this would be to create a few pull requests. @christopher-henderson would this work for you?

**Comment by mtgag** [comment]
List of pull requests:

- [ ] https://github.com/zmap/zlint/pull/711

**Comment by zakird** [comment]
Is there anything to be done for this issue or does it make sense to close it? It looks like everything is checked off.

**Comment by mtgag** [comment]
It's been a bit quiet around jzlint lately and I think we can close this. If things come up through the use of jzlint that are worth reporting, we will address them as pull requests.
