### ISSUE TITLE
Running Specific Lints on CRLs

### ISSUE THREAD

**Issue by joshschoenberg** [zmap/zlint#872]
I am trying to use ZLint in order to lint CRLs, but I want to only lint from the RFC5280 source. Based on my understanding of the ZLint code, it looks like ZLint currently does not support linting CRLs from specific sources. However, it looks like there could be an easy fix to this (including the registry as an argument to the function that runs the lint on the CRL). Am I correct about my assumptions? Is there a reason that ZLint does not currently support linting CRLs from specific sources?

**Comment by christopher-henderson** [comment]
> Is there a reason that ZLint does not currently support linting CRLs from specific sources?

Not that I am aware of. It was likely an oversight that was not found since it filter is not so commonly used by CAs,  I think. Thank you for addressing this #874 !
